=== Nielk1/dataworkshop/src/dtd/DataTransformation.dtd
<!--
    Description:
-->
<!ENTITY % DataNumber.dtd SYSTEM "DataNumber.dtd">
%DataNumber.dtd;
<!ENTITY % Data.dtd SYSTEM "Data.dtd">
%Data.dtd;
<!ENTITY % Encoding.dtd SYSTEM "Encoding.dtd">
%Encoding.dtd;

<!ELEMENT DataTransformation (transformers)>
<!ATTLIST DataTransformation
   name      CDATA #REQUIRED
   bitSize   CDATA #REQUIRED
>

<!ELEMENT transformers (AddValue | CRC32 | Convert | Decrease | Fill | FindAndReplace | Increase | Negate |Not | Rotate | Shift | SwapByteOrder | Translate)*>
<!ATTLIST transformers
>

<!--
-->
<!ELEMENT AddValue (DataNumber)>
<!ATTLIST AddValue
   value     CDATA #REQUIRED
>

<!--
    Calcutes a CRC-32 Checksum on the data.
-->
<!ELEMENT CRC32 EMPTY>

<!--
    Convert the data to a different format. The data is converted to a String 
    using the encoder. Then this String is converted back into data using the 
    decoder.
-->
<!ELEMENT Convert (Encoder, Decoder)>
<!ELEMENT Encoder (%Encoding;)>
<!ELEMENT Decoder (%Encoding;)>

<!--
-->
<!ELEMENT Decrease EMPTY>
<!ATTLIST Decrease
   value     CDATA #REQUIRED  
>

<!--
    Fills the data with a pattern.
-->
<!ELEMENT Fill (Data)>

<!--
    Fills the data with a pattern.
-->
<!ELEMENT FindAndReplace ((%Encoding;), Data, (%Encoding;), Data)>
<!ATTLIST FindAndReplace
   stepSize     CDATA #REQUIRED 
>

<!--
-->
<!ELEMENT Increase EMPTY>
<!ATTLIST Increase
   value     CDATA #REQUIRED  
>

<!--
    Does a 2-complement on the data.
-->
<!ELEMENT Negate EMPTY>

<!--
    Does a bitwise not on the data.
-->
<!ELEMENT Not EMPTY>

<!--
    Rotates the selected Data n bits. 
    bits > 0, the data is shifted "bits" to the right
    bits < 0, the data is shifted "bits" to the left.
-->
<!ELEMENT Rotate EMPTY>
<!ATTLIST Rotate
   bits     CDATA #REQUIRED
>

<!--
    Shift the selected Data n bits and fill with either 1 or 0
    bits > 0, the data is shifted "bits" to the right
    bits < 0, the data is shifted "bits" to the left.
-->
<!ELEMENT Shift EMPTY>
<!ATTLIST Shift
   bits     CDATA #REQUIRED  
   fillWithOnes  CDATA #REQUIRED
>

<!--
    Changes the byte order. Byte 0 is exchanged with byte n, byte 1 is exchanged 
    with byte n - 1, and so on. 
-->
<!ELEMENT SwapByteOrder EMPTY>
<!ATTLIST SwapByteOrder
   swappedBytes     CDATA #REQUIRED  
>

<!--
-->
<!ELEMENT Translate (DataToDataMapping)>

<!ELEMENT DataToDataMapping ((%Encoding;), Mapping) >
<!ELEMENT Mapping (Map)* >
<!ATTLIST Mapping
    bitSize      CDATA #REQUIRED
>
<!ELEMENT Map EMPTY >
<!ATTLIST Map
    from      CDATA #REQUIRED
    to        CDATA #REQUIRED
>

=== Nielk1/dataworkshop/src/transformations/toUpperCase.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE DataTransformation SYSTEM 'dtd/DataTransformation.dtd'>
<DataTransformation name="To Uppercase" bitSize="8">
<transformers>
<Translate>
<DataToDataMapping>
<IntegerEncoding radix="16" littleEndian="false" bitSize="8" signed="false"/>
<Mapping bitSize="8">
<Map from="7A" to="5A"/>
<Map from="6D" to="4D"/>
<Map from="6C" to="4C"/>
<Map from="6B" to="4B"/>
<Map from="6A" to="4A"/>
<Map from="69" to="49"/>
<Map from="68" to="48"/>
<Map from="67" to="47"/>
<Map from="66" to="46"/>
<Map from="65" to="45"/>
<Map from="64" to="44"/>
<Map from="63" to="43"/>
<Map from="62" to="42"/>
<Map from="61" to="41"/>
<Map from="6E" to="4E"/>
<Map from="6F" to="4F"/>
<Map from="70" to="50"/>
<Map from="71" to="51"/>
<Map from="72" to="52"/>
<Map from="73" to="53"/>
<Map from="74" to="54"/>
<Map from="75" to="55"/>
<Map from="76" to="56"/>
<Map from="77" to="57"/>
<Map from="78" to="58"/>
<Map from="79" to="59"/>
</Mapping>
</DataToDataMapping>
</Translate>
</transformers>
</DataTransformation>
